---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: api-test-for-flux
  namespace: fluxcd
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: api-test-for-flux
  forceUpgrade: true
  timeout: 300 #300 is default even if not specified
  wait: true
  maxHistory: 10
  git:
    timeout: 300s
  chart:
    git: git@github.com:debapratim-dey/helm-intoduction
    ref: master
    path: api-chart/
  values:
    image:
      repository: deb0pratim/dummy_flask_app
      tag: "1.3"
