apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: flask
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: flask-ctr
        image: deb0pratim/dummy_flask_app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000